In [1]:
import os
import numpy as np
import pandas as pd
from scipy.stats import skew, kurtosis
import cv2
import glob
import tifffile as tiff
import matplotlib.pyplot as plt

In [2]:
R_LPA = np.loadtxt("R_LPA.txt")
L_LPA = np.loadtxt("L_LPA.txt")
    
LPA = np.concatenate((L_LPA, R_LPA))
LPA_all_mean = np.mean(LPA)
LPA_all_std = np.std(LPA)
LPA_all_max = np.max(LPA)
LPA_all_min = np.min(LPA)
LPA_all_skew = skew(LPA)
LPA_all_kurtosis = kurtosis(LPA)

# Initialize data of lists
data = {'Variables':['LPA_all_mean','LPA_all_std','LPA_all_max','LPA_all_min','LPA_all_skew','LPA_all_kurtosis'],
        'Values': [LPA_all_mean,LPA_all_std,LPA_all_max,LPA_all_min,LPA_all_skew,LPA_all_kurtosis]}
  
# Create DataFrame
df = pd.DataFrame(data)
display(df)

df.to_csv('LPA_all.csv', index=False)

          Variables     Values
0      LPA_all_mean  23.950621
1       LPA_all_std   4.132753
2       LPA_all_max  32.803284
3       LPA_all_min   0.019600
4      LPA_all_skew  -1.733794
5  LPA_all_kurtosis   7.033370

In [3]:
mean = ([25.7, 23.950621])
std = ([1.3, 4.132753])

astd = np.sqrt(((39*std[0]*std[0]) + (21*std[1]*std[1]))/(40+22-2))
print(np.mean(mean), astd)
print(np.mean(std))
print(np.std(mean))

24.8253105 2.6601459688620754
2.7163765
0.8746894999999988

# Extraer Classes left angiosome

In [4]:
# Define range
c1_L = L_LPA[(L_LPA >= 28) & (L_LPA < 29)]
c2_L = L_LPA[(L_LPA >= 29) & (L_LPA < 30)]
c3_L = L_LPA[(L_LPA >= 30) & (L_LPA < 31)]
c4_L = L_LPA[(L_LPA >= 31) & (L_LPA < 32)]
c5_L = L_LPA[(L_LPA >= 32) & (L_LPA < 33)]
c6_L = L_LPA[(L_LPA >= 33) & (L_LPA < 34)]
c7_L = L_LPA[(L_LPA >= 34) & (L_LPA < 35)]

c1_R = R_LPA[(R_LPA >= 28) & (R_LPA < 29)]
c2_R = R_LPA[(R_LPA >= 29) & (R_LPA < 30)]
c3_R = R_LPA[(R_LPA >= 30) & (R_LPA < 31)]
c4_R = R_LPA[(R_LPA >= 31) & (R_LPA < 32)]
c5_R = R_LPA[(R_LPA >= 32) & (R_LPA < 33)]
c6_R = R_LPA[(R_LPA >= 33) & (R_LPA < 34)]
c7_R = R_LPA[(R_LPA >= 34) & (R_LPA < 35)]

# Extract number of elements per range
Total_L = len(L_LPA)
Total_c1_L = len(c1_L)
Total_c2_L = len(c2_L)
Total_c3_L = len(c3_L)
Total_c4_L = len(c4_L)
Total_c5_L = len(c5_L)
Total_c6_L = len(c6_L)
Total_c7_L = len(c7_L)

Total_R = len(R_LPA)
Total_c1_R = len(c1_R)
Total_c2_R = len(c2_R)
Total_c3_R = len(c3_R)
Total_c4_R = len(c4_R)
Total_c5_R = len(c5_R)
Total_c6_R = len(c6_R)
Total_c7_R = len(c7_R)

# Extract percentages
per_c1_L = (len(c1_L)*100)/len(L_LPA)
per_c2_L = (len(c2_L)*100)/len(L_LPA)
per_c3_L = (len(c3_L)*100)/len(L_LPA)
per_c4_L = (len(c4_L)*100)/len(L_LPA)
per_c5_L = (len(c5_L)*100)/len(L_LPA)
per_c6_L = (len(c6_L)*100)/len(L_LPA)
per_c7_L = (len(c7_L)*100)/len(L_LPA)

per_c1_R = (len(c1_R)*100)/len(R_LPA)
per_c2_R = (len(c2_R)*100)/len(R_LPA)
per_c3_R = (len(c3_R)*100)/len(R_LPA)
per_c4_R = (len(c4_R)*100)/len(R_LPA)
per_c5_R = (len(c5_R)*100)/len(R_LPA)
per_c6_R = (len(c6_R)*100)/len(R_LPA)
per_c7_R = (len(c7_R)*100)/len(R_LPA)

# Extract ETs
ET_L_LPA = ((28.5*per_c1_L) + (29.5*per_c2_L))/(per_c1_L+per_c2_L)
ET_R_LPA = ((28.5*per_c1_R) + (29.5*per_c2_R))/(per_c1_R+per_c2_R)

# Extract HSE
Cl_L_LPA = np.max(L_LPA)
Cl_R_LPA = np.max(R_LPA)

HSE_L_LPA = abs(Cl_L_LPA - ET_L_LPA)
HSE_R_LPA = abs(Cl_R_LPA - ET_R_LPA)

# Extract ETD
ETD_LPA = abs(ET_L_LPA - ET_R_LPA)

# Initialize data of lists
data2 = {'Temperatures':['---',28.5, 29.5, 30.5, 31, 32.5, 33.5, 34.5],
         'Variables_L':['Total_L_LPA','c1_L_LPA', 'c2_L_LPA', 'c3_L_LPA', 'c4_L_LPA', 'c5_L_LPA', 'c6_L_LPA', 'c7_L_LPA'],
         'Numel_L':[len(L_LPA), len(c1_L), len(c2_L), len(c3_L), len(c4_L), len(c5_L), len(c6_L), len(c7_L)],
         'Percentages_L': ['---', per_c1_L,per_c2_L,per_c3_L,per_c4_L,per_c5_L,per_c6_L,per_c7_L],
         'ET_L': [ET_L_LPA, '---', '---', '---', '---', '---', '---', '---'],
         'HSE_L': [HSE_L_LPA, '---', '---', '---', '---', '---', '---', '---'],
         'Variables_R':['Total_R_LPA','c1_R_LPA', 'c2_R_LPA', 'c3_R_LPA', 'c4_R_LPA', 'c5_R_LPA', 'c6_R_LPA', 'c7_R_LPA'],
         'Numel_R':[len(R_LPA), len(c1_R), len(c2_R), len(c3_R), len(c4_R), len(c5_R), len(c6_R), len(c7_R)],
         'Percentages_R': ['---', per_c1_R,per_c2_R,per_c3_R,per_c4_R,per_c5_R,per_c6_R,per_c7_R],
         'ET_R': [ET_R_LPA, '---', '---', '---', '---', '---', '---', '---'],
         'HSE_R': [HSE_R_LPA, '---', '---', '---', '---', '---', '---', '---'],
         'ETD': [ETD_LPA, '---', '---', '---', '---', '---', '---', '---']}
  
# Create DataFrame
df2 = pd.DataFrame(data2)
display(df2)

df2.to_csv('LPA_ET.csv', index=False)

,Temperatures,Variables_L,Numel_L,Percentages_L,ET_L,HSE_L,Variables_R,Numel_R,Percentages_R,ET_R,HSE_R,ETD
0,---,Total_L_LPA,200473,---,28.891327,3.680549,Total_R_LPA,191304,---,28.842629,3.960654,0.048698
1,28.5,c1_L_LPA,9292,4.635038,---,---,c1_R_LPA,11621,6.074625,---,---,---
2,29.5,c2_L_LPA,5974,2.979952,---,---,c2_R_LPA,6057,3.166165,---,---,---
3,30.5,c3_L_LPA,5196,2.59187,---,---,c3_R_LPA,3692,1.929913,---,---,---
4,31,c4_L_LPA,2740,1.366768,---,---,c4_R_LPA,3146,1.644503,---,---,---
5,32.5,c5_L_LPA,442,0.220479,---,---,c5_R_LPA,368,0.192364,---,---,---
6,33.5,c6_L_LPA,0,0.0,---,---,c6_R_LPA,0,0.0,---,---,---
7,34.5,c7_L_LPA,0,0.0,---,---,c7_R_LPA,0,0.0,---,---,---