In [1]:
import os
import numpy as np
import pandas as pd
from scipy.stats import skew, kurtosis
import cv2
import glob
import tifffile as tiff
import matplotlib.pyplot as plt

In [2]:
R_MCA = np.loadtxt("R_MCA.txt")
L_MCA = np.loadtxt("L_MCA.txt")
    
MCA = np.concatenate((L_MCA, R_MCA))
MCA_all_mean = np.mean(MCA)
MCA_all_std = np.std(MCA)
MCA_all_max = np.max(MCA)
MCA_all_min = np.min(MCA)
MCA_all_skew = skew(MCA)
MCA_all_kurtosis = kurtosis(MCA)

# Initialize data of lists
data = {'Variables':['MCA_all_mean','MCA_all_std','MCA_all_max','MCA_all_min','MCA_all_skew','MCA_all_kurtosis'],
        'Values': [MCA_all_mean,MCA_all_std,MCA_all_max,MCA_all_min,MCA_all_skew,MCA_all_kurtosis]}
  
# Create DataFrame
df = pd.DataFrame(data)
display(df)

df.to_csv('MCA_all.csv', index=False)

          Variables     Values
0      MCA_all_mean  23.914728
1       MCA_all_std   3.977407
2       MCA_all_max  30.798607
3       MCA_all_min   0.019947
4      MCA_all_skew  -2.609697
5  MCA_all_kurtosis  10.994100

In [3]:
mean = ([26.4, 23.914728])
std = ([1.3, 3.977407])

astd = np.sqrt(((39*std[0]*std[0]) + (21*std[1]*std[1]))/(40+22-2))
print(np.mean(mean), astd)
print(np.mean(std))
print(np.std(mean))

25.157364 2.575930561035594
2.6387035
1.2426359999999992

# Extraer Classes left angiosome

In [4]:
# Define range
c1_L = L_MCA[(L_MCA >= 28) & (L_MCA < 29)]
c2_L = L_MCA[(L_MCA >= 29) & (L_MCA < 30)]
c3_L = L_MCA[(L_MCA >= 30) & (L_MCA < 31)]
c4_L = L_MCA[(L_MCA >= 31) & (L_MCA < 32)]
c5_L = L_MCA[(L_MCA >= 32) & (L_MCA < 33)]
c6_L = L_MCA[(L_MCA >= 33) & (L_MCA < 34)]
c7_L = L_MCA[(L_MCA >= 34) & (L_MCA < 35)]

c1_R = R_MCA[(R_MCA >= 28) & (R_MCA < 29)]
c2_R = R_MCA[(R_MCA >= 29) & (R_MCA < 30)]
c3_R = R_MCA[(R_MCA >= 30) & (R_MCA < 31)]
c4_R = R_MCA[(R_MCA >= 31) & (R_MCA < 32)]
c5_R = R_MCA[(R_MCA >= 32) & (R_MCA < 33)]
c6_R = R_MCA[(R_MCA >= 33) & (R_MCA < 34)]
c7_R = R_MCA[(R_MCA >= 34) & (R_MCA < 35)]

# Extract number of elements per range
Total_L = len(L_MCA)
Total_c1_L = len(c1_L)
Total_c2_L = len(c2_L)
Total_c3_L = len(c3_L)
Total_c4_L = len(c4_L)
Total_c5_L = len(c5_L)
Total_c6_L = len(c6_L)
Total_c7_L = len(c7_L)

Total_R = len(R_MCA)
Total_c1_R = len(c1_R)
Total_c2_R = len(c2_R)
Total_c3_R = len(c3_R)
Total_c4_R = len(c4_R)
Total_c5_R = len(c5_R)
Total_c6_R = len(c6_R)
Total_c7_R = len(c7_R)

# Extract percentages
per_c1_L = (len(c1_L)*100)/len(L_MCA)
per_c2_L = (len(c2_L)*100)/len(L_MCA)
per_c3_L = (len(c3_L)*100)/len(L_MCA)
per_c4_L = (len(c4_L)*100)/len(L_MCA)
per_c5_L = (len(c5_L)*100)/len(L_MCA)
per_c6_L = (len(c6_L)*100)/len(L_MCA)
per_c7_L = (len(c7_L)*100)/len(L_MCA)

per_c1_R = (len(c1_R)*100)/len(R_MCA)
per_c2_R = (len(c2_R)*100)/len(R_MCA)
per_c3_R = (len(c3_R)*100)/len(R_MCA)
per_c4_R = (len(c4_R)*100)/len(R_MCA)
per_c5_R = (len(c5_R)*100)/len(R_MCA)
per_c6_R = (len(c6_R)*100)/len(R_MCA)
per_c7_R = (len(c7_R)*100)/len(R_MCA)

# Extract ETs
ET_L_MCA = ((28.5*per_c1_L) + (29.5*per_c2_L))/(per_c1_L+per_c2_L)
ET_R_MCA = ((28.5*per_c1_R) + (29.5*per_c2_R))/(per_c1_R+per_c2_R)

# Extract HSE
Cl_L_MCA = np.max(L_MCA)
Cl_R_MCA = np.max(R_MCA)

HSE_L_MCA = abs(Cl_L_MCA - ET_L_MCA)
HSE_R_MCA = abs(Cl_R_MCA - ET_R_MCA)

# Extract ETD
ETD_MCA = abs(ET_L_MCA - ET_R_MCA)

# Initialize data of lists
data2 = {'Temperatures':['---',28.5, 29.5, 30.5, 31, 32.5, 33.5, 34.5],
         'Variables_L':['Total_L_MCA','c1_L_MCA', 'c2_L_MCA', 'c3_L_MCA', 'c4_L_MCA', 'c5_L_MCA', 'c6_M_LCA', 'c7_M_LCA'],
         'Numel_L':[len(L_MCA), len(c1_L), len(c2_L), len(c3_L), len(c4_L), len(c5_L), len(c6_L), len(c7_L)],
         'Percentages_L': ['---', per_c1_L,per_c2_L,per_c3_L,per_c4_L,per_c5_L,per_c6_L,per_c7_L],
         'ET_L': [ET_L_MCA, '---', '---', '---', '---', '---', '---', '---'],
         'HSE_L': [HSE_L_MCA, '---', '---', '---', '---', '---', '---', '---'],
         'Variables_R':['Total_R_MCA','c1_R_MCA', 'c2_R_MCA', 'c3_R_MCA', 'c4_R_MCA', 'c5_R_MCA', 'c6_R_MCA', 'c7_R_MCA'],
         'Numel_R':[len(R_MCA), len(c1_R), len(c2_R), len(c3_R), len(c4_R), len(c5_R), len(c6_R), len(c7_R)],
         'Percentages_R': ['---', per_c1_R,per_c2_R,per_c3_R,per_c4_R,per_c5_R,per_c6_R,per_c7_R],
         'ET_R': [ET_R_MCA, '---', '---', '---', '---', '---', '---', '---'],
         'HSE_R': [HSE_R_MCA, '---', '---', '---', '---', '---', '---', '---'],
         'ETD': [ETD_MCA, '---', '---', '---', '---', '---', '---', '---']}
  
# Create DataFrame
df2 = pd.DataFrame(data2)
display(df2)

df2.to_csv('MCA_ET.csv', index=False)

,Temperatures,Variables_L,Numel_L,Percentages_L,ET_L,HSE_L,Variables_R,Numel_R,Percentages_R,ET_R,HSE_R,ETD
0,---,Total_L_MCA,66132,---,28.788945,2.009662,Total_R_MCA,59724,---,28.717404,1.057232,0.071541
1,28.5,c1_L_MCA,2264,3.423456,---,---,c1_R_MCA,5486,9.185587,---,---,---
2,29.5,c2_L_MCA,920,1.391157,---,---,c2_R_MCA,1524,2.551738,---,---,---
3,30.5,c3_L_MCA,845,1.277748,---,---,c3_R_MCA,0,0.0,---,---,---
4,31,c4_L_MCA,0,0.0,---,---,c4_R_MCA,0,0.0,---,---,---
5,32.5,c5_L_MCA,0,0.0,---,---,c5_R_MCA,0,0.0,---,---,---
6,33.5,c6_M_LCA,0,0.0,---,---,c6_R_MCA,0,0.0,---,---,---
7,34.5,c7_M_LCA,0,0.0,---,---,c7_R_MCA,0,0.0,---,---,---