In [1]:
import os
import numpy as np
import pandas as pd
from scipy.stats import skew, kurtosis
import cv2
import glob
import tifffile as tiff
import matplotlib.pyplot as plt

In [2]:
R_LCA = np.loadtxt("R_LCA.txt")
L_LCA = np.loadtxt("L_LCA.txt")
    
LCA = np.concatenate((L_LCA, R_LCA))
LCA_all_mean = np.mean(LCA)
LCA_all_std = np.std(LCA)
LCA_all_max = np.max(LCA)
LCA_all_min = np.min(LCA)
LCA_all_skew = skew(LCA)
LCA_all_kurtosis = kurtosis(LCA)

# Initialize data of lists
data = {'Variables':['LCA_all_mean', 'LCA_all_std', 'LCA_all_max', 'LCA_all_min', 'LCA_all_skew', 
                     'LCA_all_kurtosis'],
         'Values': [LCA_all_mean, LCA_all_std, LCA_all_max, LCA_all_min, LCA_all_skew, LCA_all_kurtosis]}
  
# Create DataFrame
df = pd.DataFrame(data)
display(df)

df.to_csv('LCA_all.csv', index=False)

          Variables     Values
0      LCA_all_mean  23.946718
1       LCA_all_std   3.990466
2       LCA_all_max  31.685932
3       LCA_all_min   0.040357
4      LCA_all_skew  -2.553002
5  LCA_all_kurtosis  10.769025

In [3]:
mean = ([26.1, 23.946718])
std = ([1.4, 3.990466])

astd = np.sqrt(((39*std[0]*std[0]) + (21*std[1]*std[1]))/(40+22-2))
print(np.mean(mean), astd)
print(np.mean(std))
print(np.std(mean))

25.023359 2.616741602452294
2.695233
1.0766410000000004

# Extraer Classes left angiosome

In [4]:
# Define range
c1_L = L_LCA[(L_LCA >= 28) & (L_LCA < 29)]
c2_L = L_LCA[(L_LCA >= 29) & (L_LCA < 30)]
c3_L = L_LCA[(L_LCA >= 30) & (L_LCA < 31)]
c4_L = L_LCA[(L_LCA >= 31) & (L_LCA < 32)]
c5_L = L_LCA[(L_LCA >= 32) & (L_LCA < 33)]
c6_L = L_LCA[(L_LCA >= 33) & (L_LCA < 34)]
c7_L = L_LCA[(L_LCA >= 34) & (L_LCA < 35)]

c1_R = R_LCA[(R_LCA >= 28) & (R_LCA < 29)]
c2_R = R_LCA[(R_LCA >= 29) & (R_LCA < 30)]
c3_R = R_LCA[(R_LCA >= 30) & (R_LCA < 31)]
c4_R = R_LCA[(R_LCA >= 31) & (R_LCA < 32)]
c5_R = R_LCA[(R_LCA >= 32) & (R_LCA < 33)]
c6_R = R_LCA[(R_LCA >= 33) & (R_LCA < 34)]
c7_R = R_LCA[(R_LCA >= 34) & (R_LCA < 35)]

# Extract number of elements per range
Total_L = len(L_LCA)
Total_c1_L = len(c1_L)
Total_c2_L = len(c2_L)
Total_c3_L = len(c3_L)
Total_c4_L = len(c4_L)
Total_c5_L = len(c5_L)
Total_c6_L = len(c6_L)
Total_c7_L = len(c7_L)

Total_R = len(R_LCA)
Total_c1_R = len(c1_R)
Total_c2_R = len(c2_R)
Total_c3_R = len(c3_R)
Total_c4_R = len(c4_R)
Total_c5_R = len(c5_R)
Total_c6_R = len(c6_R)
Total_c7_R = len(c7_R)

# Extract percentages
per_c1_L = (len(c1_L)*100)/len(L_LCA)
per_c2_L = (len(c2_L)*100)/len(L_LCA)
per_c3_L = (len(c3_L)*100)/len(L_LCA)
per_c4_L = (len(c4_L)*100)/len(L_LCA)
per_c5_L = (len(c5_L)*100)/len(L_LCA)
per_c6_L = (len(c6_L)*100)/len(L_LCA)
per_c7_L = (len(c7_L)*100)/len(L_LCA)

per_c1_R = (len(c1_R)*100)/len(R_LCA)
per_c2_R = (len(c2_R)*100)/len(R_LCA)
per_c3_R = (len(c3_R)*100)/len(R_LCA)
per_c4_R = (len(c4_R)*100)/len(R_LCA)
per_c5_R = (len(c5_R)*100)/len(R_LCA)
per_c6_R = (len(c6_R)*100)/len(R_LCA)
per_c7_R = (len(c7_R)*100)/len(R_LCA)

# Extract ETs
ET_L_LCA = ((28.5*per_c1_L) + (29.5*per_c2_L))/(per_c1_L+per_c2_L)
ET_R_LCA = ((28.5*per_c1_R) + (29.5*per_c2_R))/(per_c1_R+per_c2_R)

# Extract HSE
Cl_L_LCA = np.max(L_LCA)
Cl_R_LCA = np.max(R_LCA)

HSE_L_LCA = abs(Cl_L_LCA - ET_L_LCA)
HSE_R_LCA = abs(Cl_R_LCA - ET_R_LCA)

# Extract ETD
ETD_LCA = abs(ET_L_LCA - ET_R_LCA)

# Initialize data of lists
data2 = {'Temperatures':['---',28.5, 29.5, 30.5, 31, 32.5, 33.5, 34.5],
         'Variables_L':['Total_L_LCA','c1_L_LCA', 'c2_L_LCA', 'c3_L_LCA', 'c4_L_LCA', 'c5_L_LCA', 'c6_L_LCA', 'c7_L_LCA'],
         'Numel_L':[len(L_LCA), len(c1_L), len(c2_L), len(c3_L), len(c4_L), len(c5_L), len(c6_L), len(c7_L)],
         'Percentages_L': ['---', per_c1_L,per_c2_L,per_c3_L,per_c4_L,per_c5_L,per_c6_L,per_c7_L],
         'ET_L': [ET_L_LCA, '---', '---', '---', '---', '---', '---', '---'],
         'HSE_L': [HSE_L_LCA, '---', '---', '---', '---', '---', '---', '---'],
         'Variables_R':['Total_R_LCA','c1_R_LCA', 'c2_R_LCA', 'c3_R_LCA', 'c4_R_LCA', 'c5_R_LCA', 'c6_R_LCA', 'c7_R_LCA'],
         'Numel_R':[len(R_LCA), len(c1_R), len(c2_R), len(c3_R), len(c4_R), len(c5_R), len(c6_R), len(c7_R)],
         'Percentages_R': ['---', per_c1_R,per_c2_R,per_c3_R,per_c4_R,per_c5_R,per_c6_R,per_c7_R],
         'ET_R': [ET_R_LCA, '---', '---', '---', '---', '---', '---', '---'],
         'HSE_R': [HSE_R_LCA, '---', '---', '---', '---', '---', '---', '---'],
         'ETD': [ETD_LCA, '---', '---', '---', '---', '---', '---', '---']}
  
# Create DataFrame
df2 = pd.DataFrame(data2)
display(df2)

df2.to_csv('LCA_ET.csv', index=False)

,Temperatures,Variables_L,Numel_L,Percentages_L,ET_L,HSE_L,Variables_R,Numel_R,Percentages_R,ET_R,HSE_R,ETD
0,---,Total_L_LCA,62276,---,28.830677,2.855256,Total_R_LCA,63719,---,28.946671,1.25653,0.115994
1,28.5,c1_L_LCA,4115,6.607682,---,---,c1_R_LCA,2651,4.160454,---,---,---
2,29.5,c2_L_LCA,2033,3.2645,---,---,c2_R_LCA,2140,3.358496,---,---,---
3,30.5,c3_L_LCA,239,0.383775,---,---,c3_R_LCA,47,0.073761,---,---,---
4,31,c4_L_LCA,10,0.016058,---,---,c4_R_LCA,0,0.0,---,---,---
5,32.5,c5_L_LCA,0,0.0,---,---,c5_R_LCA,0,0.0,---,---,---
6,33.5,c6_L_LCA,0,0.0,---,---,c6_R_LCA,0,0.0,---,---,---
7,34.5,c7_L_LCA,0,0.0,---,---,c7_R_LCA,0,0.0,---,---,---